---
- hosts: all
  become: yes # This means that all tasks will be executed with sudo
  vars:
    prj_path: "/vagrant"
    python_ver: 3.6
 
    ansible_distribution_release: bionic
    theuser: vagrant
    ansible_python_interpreter: /usr/bin/python3

    
  roles:
  - {role: python}